# Site settings
title: Gabriele Belli
email: belligabriele91@gmail.com
url: gabrielebelli.github.io
description: "Un simpatico ingegnere informatico guidato dalla 
passione per la Sicurezza Informatica ed i Big Data. "
# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#ffffff'

# Footer settings
footer: Gabriele Belli

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://linkedin.com/in/gabrielebelli/
  - title: bitbucket
    url: https://bitbucket.org/gabrielebelli/
  - title: facebook
    url: https://www.facebook.com/GabrieleBelli91
  - title: instagram
    url: https://www.instagram.com/gabriele391/

# Build settings
markdown: Gabriele Belli
permalink: Gabriele Belli
